name: jarv
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  floor: ^1.4.2
  floor_generator: ^1.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_speed_dial: ^7.0.0
  get_it: ^7.6.7
  multiple_stream_builder: ^3.0.2
  provider: ^6.1.2
  flutter_animated_icons: ^1.0.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
